### ISSUE TITLE
G29 / Leveling does not function

### ISSUE THREAD

**Issue by idnthvn** [Darkwulf183/Marlin-2.0.8-ALL-UI-Standart-Color-LVGL#1]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Tested this version of yours. When taping the LEVELING screen, Does nothing. 
When i run the G29 code, it freezes and does nothing. 

Tronxy X5sa 400-2E

### Version of Marlin Firmware

2.0.8

### Printer model

x5sa 400 2e

**Comment by Darkwulf183** [comment]
Hello, 

What exactly is that supposed to tell me? They don't even write in which UI they use. With the lvgl ui, the g29 and m600 don't work. The g29 is bugged by marlin. There is nothing I can do about that. And as far as I know, everything works with the colour UI. Printers with dual extruders are critical with this board anyway - some have already had problems. But I can't test that myself. And I can't fix any marlin errors either. I only maintain my own repository for tronxy.

Translated with www.Deepl.com

**Comment by idnthvn** [comment]
Okay, was unaware that the leveling in 2.0.8 is buggy. I had it once, but i did not know there was no UI in it. I suppose i will go back to the colour UI instead :/ was hoping to have the LVGL UI as it looks neater.
Thanks though

**Comment by Darkwulf183** [comment]
No issue, many simply don't use an auto bed level with the lvgl. I'm slowly but steadily switching to clipper and bigtreetech skr 1.4. the possibilities are simply many times greater and various errors disappear because you just don't do anything via the board.... But I only work with the colour ui. I don't need this fancy display stuff the thing has to print and earn money ;)
